# Generated by Django 3.1.7 on 2021-03-05 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'List',
                'verbose_name_plural': 'Lists',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(blank=True, max_length=255, null=True, verbose_name='Task')),
                ('created', models.DateField(verbose_name='Created')),
                ('due_on', models.DateField(verbose_name='Due on')),
                ('owner', models.CharField(blank=True, max_length=255, null=True, verbose_name='Owner')),
                ('mark', models.BooleanField(verbose_name='Mark')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='tasks', to='main.list', verbose_name='List')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
            },
        ),
    ]
